### ISSUE TITLE
retrieve specific info about the incidents and fire stations?

### ISSUE THREAD

**Issue by rgdonohue** [Jack150/seattlefire-and-medicalevents#5]
Can the user retrieve specific info about these by hovering or clicking on the icons. The names/addresses of the fire stations may be useful, for example

**Comment by Jack150** [comment]
I am having trouble getting the bindToolTip to work on the stations.

**Comment by Jack150** [comment]
Fire Station Information is not critical to the map.  The planners just need to know that one is in the vicinity of the incidents.
